# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoodEats' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoodEats
  pod 'Parse'
  pod 'HCSStarRatingView', '~> 1.5'
  pod 'DateTools'
  pod 'YelpAPI'


  target 'GoodEatsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoodEatsUITests' do
    # Pods for testing
  end

end
